### ISSUE TITLE
[tab utilities addon] missing arrow? 

### ISSUE THREAD

**Issue by Skrell** [Lootyhoof/australium#2]
Hi again, I'm sorry to keep bugging you but I was hoping you might have some CSS that would allow me to add back in the expandable arrow on tabs that have been "stacked" using tab utilities (one of the greatest addons ever btw).

**Comment by Lootyhoof** [comment]
I'm not sure what you're referring to here. Could you explain how such a feature is enabled in the addon? I'm not typically a user of this addon, sadly.

**Comment by Skrell** [comment]
So basically "tab stacking" allows you to drag a bunch of tabs on top of
each other and then expand and collapse them with the push of a little
arrow icon on the right side of the tab.   Here is a pic of a collapsed tab
stack.  Note that i circled where the arrow icon should be; however,
something in your CSS is removing/hiding it.
http://oi68.tinypic.com/28jussl.jpg

**Comment by Lootyhoof** [comment]
5637d2cdbd44bdefde06875c093c702243c5eac4 should introduce the fix for this. Can you confirm?

**Comment by Skrell** [comment]
How do i test it?

**Comment by Skrell** [comment]
Never mind figured it out and it works perfectly!   My only suggestion
would be to move the icon like maybe 4 pixels to the left.  THANK YOU SO
MUCH for your wonderful theme and even more wonderful support!   You are
truly a special person!
