### ISSUE TITLE
No bookmark stars in the awesomebar dropdown

### ISSUE THREAD

**Issue by Skrell** [Lootyhoof/australium#4]
I knew something was missing...when i type in a url i never see any stars to indicate which results are history and which are bookmarks.

**Comment by Lootyhoof** [comment]
This is not a feature of Pale Moon, as far as I can tell. Not sure of any extensions that could add this, but there may be some.

In any event, not an issue for this theme.

**Comment by Skrell** [comment]
If I disable your theme and use the default one the stars for bookmarked
urls in the awesomebar dropdown are there.   I can send you a picture if
you'd like but it definitely appears to be something in your theme that's
removing them.

**Comment by Skrell** [comment]
![untitled](https://cloud.githubusercontent.com/assets/590266/14588951/9a48c300-04a4-11e6-985e-4b10fc4a6b57.jpg)

**Comment by Lootyhoof** [comment]
Interesting, my mistake. I'll take a look into this ASAP.

**Comment by Skrell** [comment]
Thank you friend! Your theme is going to be the most perfect one ever! ;-)

**Comment by Lootyhoof** [comment]
Should be fixed as of e97861c507939a2e630f33bb915efe6ff79a97b6. I'll be making a release soon, in any case.

**Comment by Skrell** [comment]
Awesome!
